// <auto-generated />
namespace ConnectedDot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonalSkills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonalSkills));
        
        string IMigrationMetadata.Id
        {
            get { return "201708091233465_PersonalSkills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
